#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

layout (std430, binding = 0) readonly buffer MatrixIn   { float matrix[];            };
layout (std430, binding = 1)          buffer MatrixOut  { float transposed_matrix[]; };

layout (push_constant) uniform PushConstants {
    uint w;
    uint h;
} params;

layout (local_size_x = 1, local_size_y = 1) in;
void main()
{
    // TODO
}
