#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

layout (std430, binding = 0) readonly  buffer ValuesIn  { uint input_data[];  };
layout (std430, binding = 1) writeonly buffer ValuesOut { uint output_data[]; };

layout (push_constant) uniform PushConstants {
    int sorted_k;
    int n;
} params;

layout (local_size_x = 1) in;
void main()
{
    const uint i = gl_GlobalInvocationID.x;
    // TODO
}
